version: '3.8'

services:
  postgres:
    image: postgres:latest  # Используйте нужную версию PostgreSQL
    container_name: my_postgres
    env_file: 
      - ./.env  # Подключение файла с переменными окружения
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Сохранение данных PostgreSQL
      - ./initdb:/docker-entrypoint-initdb.d/  # Скрипты, запускаемые при инициализации
    ports:
      - "5432:5432"  # Порт на хосте и в контейнере

  # Сервис Parser-server
  parser-server:
    container_name: parser-server
    build: ./parser-service/
    depends_on:
      - postgres  # Этот сервис зависит от PostgreSQL
    volumes:
      - ./parser-service/Data:/parser-service/Data
    restart: unless-stopped
    ports:
      - "8000:8000"  # Порт, по которому доступен FastAPI
    env_file:
       - ./parser-service/.env
  