FROM python:3.12

ARG SERVICE_DIR=parser-service

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1


WORKDIR /app


COPY $SERVICE_DIR/poetry.lock $SERVICE_DIR/pyproject.toml /app/

RUN pip install poetry


RUN poetry lock --no-update

RUN poetry config virtualenvs.create false && \
    poetry install
